services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      # TODO: こちら必要なのかを確認
      - /app/node_modules
      # yarn workspaces 使用時、パッケージの実体はルートの node_modules にインストールされる
      # frontend/node_modules/.bin/* は ../../../node_modules/* へのシンボリックリンクとなる
      # コンテナ内では /app/node_modules/.bin/* が /node_modules/* を参照するため、
      # ルートの node_modules をマウントしないとパッケージが見つからずエラーになる
      # TODO:backendも必要になったら対応する
      - ./node_modules:/node_modules
    environment:
      - NODE_ENV=development
    command: yarn dev
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/notion_clone
    # Prisma Clientはnode_modulesに生成されるが、コンテナ再起動で消えるため起動時に毎回生成が必要
    command: sh -c "npx prisma generate && yarn dev"
    depends_on:
      - db

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=notion_clone

volumes:
  postgres_data:
