# 一旦最低限に絞っている
# TODO: キャッシュ
# TODO: 変更ファイルだけlint
name: Lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          # cache: "yarn"

      # - run: yarn install --prefer-offline
      - run: yarn install

      - run: yarn lint
